### ISSUE TITLE
New .reRender causing Error:  route <blah> requires a callback

### ISSUE THREAD

**Issue by probedb** [glenjamin/skin-deep#85]
Updating from 0.16.0 and everything works except reRender. Not sure if you remember any of the routes codebase here Glen :) But it's throwing a wobbler with reRender when we're using redux with routes. The initial render is fine.

```
> npm run test test/client/components/GameRulePage.test.js

> webappynamewebapp@1.0.0 test /Users/myUser/someorghere/webappynamewebapp
> NODE_ENV=test mocha "test/client/components/GameRulePage.test.js"

/Users/myUser/someorghere/webappynamewebapp/node_modules/routes/dist/routes.js:130
      if (!fn) throw new Error(' route ' + path.toString() + ' requires a callback');
               ^

Error:  route /help/game-rules/:section requires a callback
    at Object.addRoute (/Users/myUser/someorghere/webappynamewebapp/node_modules/routes/dist/routes.js:130:22)
    at route (/Users/myUser/someorghere/webappynamewebapp/client/routes.js:4:3)
    at Object.<anonymous> (/Users/myUser/someorghere/webappynamewebapp/client/routes.js:21:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/myUser/someorghere/webappynamewebapp/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myUser/someorghere/webappynamewebapp/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myUser/someorghere/webappynamewebapp/client/actions/routing.js:1:1)
```

**Comment by probedb** [comment]
Closing, figured it out!

**Comment by glenjamin** [comment]
Good stuff :)
