### ISSUE TITLE
Support for React 16 beta

### ISSUE THREAD

**Issue by miksansegundo** [glenjamin/skin-deep#91]
New React is here!

```
Cannot find module 'react/lib/React' from 'ReactShallowRenderer.js'
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/shallow/ReactShallowRenderer.js:18:13)
```

Shallow renderer is now `react-test-renderer/shallow`, and test utils moved to `react-dom/test-utils`

More info: https://github.com/facebook/react/issues/10294#issuecomment-318210497

**Comment by miksansegundo** [comment]
I'm sorry if this issue is not related with this repo. Seems more like a jest issue.

**Comment by miksansegundo** [comment]
After update my dependencies:

- react-addons-test-utils
- react-test-renderer
- skin-deep 

It's solved.
